services:
  # backend:
  #   container_name: nestjs_backend
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   command: npm run start:dev
    # depends_on:
    #   - mysql_db
    # volumes:
    #   - ./docker_data/src:/usr/src/app/src
  
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=faculty_db
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=pass123
    volumes:
      - ./db:/var/lib/mysql # create path of sql volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_backend
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: user123
      PMA_PASSWORD: pass123
    ports:
      - "8080:80"
    depends_on:
      - mysql_db
