import { AuditLog } from 'src/generated/nestjs-dto/auditLog.entity';
import { Branch } from 'src/generated/nestjs-dto/branch.entity';
import { Clo } from 'src/generated/nestjs-dto/clo.entity';
import { Company } from 'src/generated/nestjs-dto/company.entity';
import { CompanyJobPosition } from 'src/generated/nestjs-dto/companyJobPosition.entity';
import { Coordinator } from 'src/generated/nestjs-dto/coordinator.entity';
import { Course } from 'src/generated/nestjs-dto/course.entity';
import { CourseEnrollment } from 'src/generated/nestjs-dto/courseEnrollment.entity';
import { CourseInstructor } from 'src/generated/nestjs-dto/courseInstructor.entity';
import { Curriculum } from 'src/generated/nestjs-dto/curriculum.entity';
import { CurriculumCoordinators } from 'src/generated/nestjs-dto/curriculumCoordinators.entity';
import { Faculty } from 'src/generated/nestjs-dto/faculty.entity';
import { Instructor } from 'src/generated/nestjs-dto/instructor.entity';
import { Internship } from 'src/generated/nestjs-dto/internship.entity';
import { JobPosition } from 'src/generated/nestjs-dto/jobPosition.entity';
import { Lesson } from 'src/generated/nestjs-dto/lesson.entity';
import { LevelDescription } from 'src/generated/nestjs-dto/levelDescription.entity';
import { Plo } from 'src/generated/nestjs-dto/plo.entity';
import { Skill } from 'src/generated/nestjs-dto/skill.entity';
import { SkillAssessment } from 'src/generated/nestjs-dto/skillAssessment.entity';
import { SkillCollection } from 'src/generated/nestjs-dto/skillCollection.entity';
import { SkillExpectedLevel } from 'src/generated/nestjs-dto/skillExpectedLevel.entity';
import { Student } from 'src/generated/nestjs-dto/student.entity';
import { StudentInternship } from 'src/generated/nestjs-dto/studentInternship.entity';
import { Subject } from 'src/generated/nestjs-dto/subject.entity';
import { User } from 'src/generated/nestjs-dto/user.entity';
import { Paginated } from './pagination.dto';

export class PaginatedAuditLogDto extends Paginated(AuditLog) {}
export class PaginatedBranchDto extends Paginated(Branch) {}
export class PaginatedCloDto extends Paginated(Clo) {}
export class PaginatedCompanyDto extends Paginated(Company) {}
export class PaginatedCompanyJobPositionDto extends Paginated(CompanyJobPosition) {}
export class PaginatedCoordinatorDto extends Paginated(Coordinator) {}
export class PaginatedCourseDto extends Paginated(Course) {}
export class PaginatedCourseEnrollmentDto extends Paginated(CourseEnrollment) {}
export class PaginatedCourseInstructorDto extends Paginated(CourseInstructor) {}
export class PaginatedCurriculumDto extends Paginated(Curriculum) {}
export class PaginatedCurriculumCoordinatorsDto extends Paginated(CurriculumCoordinators) {}
export class PaginatedFacultyDto extends Paginated(Faculty) {}
export class PaginatedInstructorDto extends Paginated(Instructor) {}
export class PaginatedInternshipDto extends Paginated(Internship) {}
export class PaginatedJobPositionDto extends Paginated(JobPosition) {}
export class PaginatedLessonDto extends Paginated(Lesson) {}
export class PaginatedLevelDescriptionDto extends Paginated(LevelDescription) {}
export class PaginatedPloDto extends Paginated(Plo) {}
export class PaginatedSkillDto extends Paginated(Skill) {}
export class PaginatedSkillAssessmentDto extends Paginated(SkillAssessment) {}
export class PaginatedSkillCollectionDto extends Paginated(SkillCollection) {}
export class PaginatedSkillExpectedLevelDto extends Paginated(SkillExpectedLevel) {}
export class PaginatedStudentDto extends Paginated(Student) {}
export class PaginatedStudentInternshipDto extends Paginated(StudentInternship) {}
export class PaginatedSubjectDto extends Paginated(Subject) {}
export class PaginatedUserDto extends Paginated(User) {}
